/* Generated By:JavaCC: Do not edit this line. ExprArbreConstants.java */
package jjgener;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprArbreConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTIER = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"a\"",
    "\"t\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<ENTIER>",
  };

}
